import streamlit as st
import datetime
import requests
import sys

BASE_URL = "http://localhost:8000"    # Backend endpoint



st.set_page_config(
    page_title = "Travel Planner Agentic Application",
    page_icon = "🗺️",
    layout = "wide",
    initial_sidebar_state = "expanded"    
)


st.title("AI Trip Planner")

# Initialize chat history
if "messages" not in st.session_state:
    st.session_state.messages = []

# Display chat history
st.header()

# Chat input box at bottom
with st.form(key="query_form", clear_on_submit=True):
    user_input =st.text_input("User Input", placeholder="e.g. Plan a trip to Goa for 5 days")
    submit_button = st.form_submit_button("Submit")
    
    

if submit_button and user_input.strip():
    try:
        # Show user message
        # Show thinking spinner while backend processes
        with st.spinner("Bot is Thinking..."):
            payload = {"question": user_input}
            response = requests.post(f"{BASE_URL}/query", json=payload)
            
        if response.status_code == 200:
            answer = response.json().get("answer", "No answer found")
            markdown_content = f"""# 🗺️ AI Travel Plan 
            
            # **Generated on {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}
            # **Created by: ** Atriyo's Travel Agent
            
            ---
            
            {answer}
            
            ----
            
            *This travel plan was generated by AI. Please verify all information, especially prices, operating hours, and travel requirements before booking.*
            """
            st.markdown(markdown_content)
        else:
            st.error(" Bot failed to respond: " + response.text)
            
    except Exception as e:
        raise f"The response failed due to: {e}"
    
